acs_wht_f32:
  - [[0, 1], [2], [3]]
  - [[2], [0, 1], [3]]
  - [[3], [2], [0, 1]]
  - [[3], [2], [1, 0]]

g24_78_usb2_f32:
  - [[0, 1, 2], [3]]

jw_mirimage_f32:
  - [[0, 1, 2], [3]]

spitzer_irac_f32:
  - [[0, 1], [2], [3]]

turbulence_f32:
  - [[0, 1], [2], [3]]

wave_f32:
  - [[0, 1], [2], [3]]

hdr_night_f32:
  - [[0, 3], [1], [2]]

ts_gas_f32:
  - [[0], [1, 2], [3]]

solar_wind_f32:
  - [[0], [1, 2], [3]]
  - [[0, 1, 2], [3]]
  - [[0], [1], [2], [3]]

tpch_lineitem_f32:
  - [[0, 1, 2], [3]]

tpcds_web_f32:
  - [[3], [0, 1, 2]]

tpcds_store_f32:
  - [[0, 1, 2], [3]]

tpcds_catalog_f32:
  - [[0, 1], [2], [3]]

citytemp_f32:
  - [[0, 1], [2], [3]]
  - [[2], [0, 1], [3]]
  - [[3], [2], [0, 1]]
  - [[3], [2], [1, 0]]

hst_wfc3_ir_f32:
  - [[0, 1], [2], [3]]
  - [[0, 1, 2], [3]]

hst_wfc3_uvis_f32:
  - [[0, 1], [2], [3]]
  - [[0, 1, 2], [3]]

rsim_f32:
  - [[0, 1], [2], [3]]

astro_mhd_f64:
  - [[0, 1, 2, 3, 4, 5], [6], [7]]

astro_pt_f64:
  - [[0, 1, 2, 3, 4, 5], [6], [7]]

jane_street_f64:
  - [[0, 1, 2, 3, 4, 5], [6], [7]]

msg_bt_f64:
  - [[0, 1, 2, 3, 4], [5], [6], [7]]

num_brain_f64:
  - [[2, 1, 3, 4, 0, 5], [6], [7]]

num_control_f64:
  - [[0, 1, 2, 3, 4, 5], [6], [7]]

nyc_taxi2015_f64:
  - [[6, 3, 5], [4], [2, 1, 0, 7]]

phone_gyro_f64:
  - [[3, 5], [7], [2, 1, 0, 6], [4]]

tpch_order_f64:
  - [[0, 1, 2, 3], [6], [5, 4], [7]]

tpcxbb_store_f64:
  - [[3, 1, 2], [0], [4], [6], [5], [7]]

tpcxbb_web_f64:
  - [[3, 1, 2], [0], [4], [6], [5], [7]]

wesad_chest_f64:
  - [[6, 4, 5], [7, 3, 0, 2, 1]]

default:
  - [[0], [1], [2], [3]]